# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add label to master Node
  shell: "kubectl label node {{ ansible_hostname }} kube-ovn/role=master"

- name: Install Kube-OVN related CRDs
  shell: "kubectl apply -f https://raw.githubusercontent.com/alauda/kube-ovn/{{ kube_ovn_version }}/yamls/crd.yaml"

- name: Install native OVS and OVN components
  shell: "kubectl apply -f https://raw.githubusercontent.com/alauda/kube-ovn/{{ kube_ovn_version }}/yamls/ovn.yaml"

- name: Install the Kube-OVN Controller and CNI plugins
  shell: "kubectl apply -f https://raw.githubusercontent.com/alauda/kube-ovn/{{ kube_ovn_version }}/yamls/kube-ovn.yaml"

- name: Install OpenNess daemons
  shell: "kubectl apply -f ../kube-ovn/openness.yaml"

- name: Install default network policy
  shell: "kubectl apply -f ../kube-ovn/default_network_policy.yaml"

- name: Install OVN tools
  yum:
    name: "{{ ovn_packages }}"

- name: Wait for OVN NB
  wait_for:
    path: /var/run/openvswitch/ovnnb_db.sock

- name: Configure OVN
  shell: | 
    ovn-nbctl lrp-add ovn-cluster ovn-cluster-local 02:0a:0a:0a:0a:01 192.168.1.1/24
    ovn-nbctl ls-add local
    ovn-nbctl lsp-add local local-ovn-cluster
    ovn-nbctl lsp-set-type local-ovn-cluster router
    ovn-nbctl lsp-set-addresses local-ovn-cluster 02:0a:0a:0a:0a:01
    ovn-nbctl lsp-set-options local-ovn-cluster router-port=ovn-cluster-local
    ovn-nbctl lsp-add local local-ovs-phy
    ovn-nbctl lsp-set-addresses local-ovs-phy unknown
    ovn-nbctl lsp-set-type local-ovs-phy localnet
    ovn-nbctl lsp-set-options local-ovs-phy network_name=local-network
