# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setup firewall - 6641/tcp
  ignore_errors: yes
  firewalld:
    port: 6641/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: kubernetes['mode'] == "kubeovn"
- name: Setup firewall - 6642/tcp
  ignore_errors: yes
  firewalld:
    port: 6642/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: kubernetes['mode'] == "kubeovn"
- name: Setup firewall - 6081/udp
  ignore_errors: yes
  firewalld:
    port: 6081/udp
    permanent: yes
    state: enabled
    immediate: yes
  when: kubernetes['mode'] == "kubeovn"
- name: Setup firewall - 6443/tcp
  ignore_errors: yes
  firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
- name: Setup firewall - 2379-2380/tcp
  ignore_errors: yes
  firewalld:
    port: 2379-2380/tcp
    permanent: yes
    state: enabled
    immediate: yes
- name: Setup firewall - 10250-10252/tcp
  ignore_errors: yes
  firewalld:
    port: 10250-10252/tcp
    permanent: yes
    state: enabled
    immediate: yes
