# Copyright 2019 Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: go

sudo: required

# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

services:
  - docker

before_install:
  # golangci-lint
  - curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  # Ginkgo
  - go get -u github.com/onsi/ginkgo/ginkgo

before_script:
  # Get project dependencies
  - go mod download

script:
  - make lint kubectl-install minikube-install minikube-start minikube-wait test

jobs:
    include:
      - stage: Controller UI
        language: node_js
        node_js:
          - "lts/*"
        before_script:
          - cd ui/controller
          - npm install -g yarn
        script:
          - yarn install
          - yarn build
          - yarn test
      - stage: CUPs UI
        language: node_js
        node_js:
          - "lts/*"
        before_script:
          - cd ui/cups
          - npm install -g yarn
        script:
          - yarn install
          - yarn build
          - yarn test
