version: '2'

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./artifacts/db:/var/lib/mysql
  cce:
    image: cce:latest
    build:
      context: .
      dockerfile: docker/run/Dockerfile
    depends_on:
      - mysql
    command: "${CCE_FLAGS}"
    ports:
      - 8080:8080
      - 8081:8081
      - 6514:6514
      - 8125:8125
    volumes:
      - ./artifacts/syslog.log:/syslog.log
      - ./artifacts/statsd.log:/statsd.log
      - ./artifacts:/certificates/ca
  ui:
    image: ui:latest
    build:
      context: ./ui/controller
      args:
        REACT_APP_CONTROLLER_API: "${REACT_APP_CONTROLLER_API}"
    ports:
      - 3000:80/tcp
    environment:
      REACT_APP_CONTROLLER_API: "${REACT_APP_CONTROLLER_API}"
  cups-ui:
    build:
      context: ./ui/cups
      args:
        REACT_APP_CUPS_API: "${REACT_APP_CUPS_API}"
    ports:
      - 3010:80/tcp
    environment:
      REACT_APP_CUPS_API: "${REACT_APP_CUPS_API}"

