version: '2'

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: beer
  ui:
    image: cce-ui:latest
    ports:
      - 3000:80/tcp
  cups-ui:
    image: cce-cups-ui:latest
    ports:
      - 3010:80/tcp
