version: '2'

services:

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: beer

  syslog:
    image:  balabit/syslog-ng:3.19.1
    ports:
      - 514:514/udp
    volumes:
      - ./syslog/logs:/var/log
