# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openness-config
  namespace: openness
data:
  http_proxy: ""
  https_proxy: ""

---
apiVersion: v1
kind: Service
metadata:
  name: eaa
  namespace: openness
spec:
  clusterIP: None
  selector:
    name: eaa
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eaa
  namespace: openness
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eaa
  template:
    metadata:
      labels:
        name: eaa
    spec:
      tolerations:
      - key: node-role.kube-ovn/master
        effect: NoSchedule
      initContainers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "cp /root/certs-sec/* /root/certs/"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: certs-sec
          mountPath: /root/certs-sec
        - name: certs
          mountPath: /root/certs
      containers:
      - name: eaa
        image: eaa:1.0
        imagePullPolicy: Never
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: certs
          mountPath: /home/eaa/certs/eaa
        - name: certs-sec
          mountPath: /home/eaa/certs-sec
        - name: configs
          mountPath: /home/eaa/configs
      volumes:
      - name: certs-sec
        secret:
          secretName: eaa-tls
      - name: certs
        hostPath:
          path: /etc/openness/certs/eaa
      - name: configs
        hostPath:
          path: /etc/openness/configs

---
apiVersion: v1
kind: Service
metadata:
  name: edgedns
  namespace: openness
spec:
  clusterIP: None
  selector:
    name: edgedns
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: cli
      protocol: TCP
      port: 4204
      targetPort: 4204

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edgedns
  namespace: openness
spec:
  selector:
    matchLabels:
      name: edgedns
  template:
    metadata:
      labels:
        name: edgedns
    spec:
      tolerations:
      - key: node-role.kube-ovn/master
        effect: NoSchedule
      containers:
      - name: edgedns
        image: edgednssvr:1.0
        imagePullPolicy: Never
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            add: ["NET_ADMIN"]
        args:
        - -address=:4204
        - -port=53
        - -fwdr=$(DNS_FWDR)
        volumeMounts:
        - name: edgednssvr
          mountPath: /var/lib/edgedns
        - name: run
          mountPath: /run
        - name: certs
          mountPath: /home/edgednssvr/certs
          readOnly: true
        env:
          - name: http_proxy
            valueFrom:
              configMapKeyRef:
                name: openness-config
                key: http_proxy
          - name: https_proxy
            valueFrom:
              configMapKeyRef:
                name: openness-config
                key: https_proxy
          - name: DNS_FWDR
            value: 8.8.8.8
      initContainers:
      - name: openssl
        image: emberstack/openssl:latest
        command: ["/root/certgen/entrypoint_tls.sh", "edgedns.openness", "/root/certs", "/root/CA"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ca
          mountPath: /root/CA
        - name: certs
          mountPath: /root/certs
        - name: certgen
          mountPath: /root/certgen
      volumes:
      - name: edgednssvr
        hostPath:
          path: /etc/openness/edgednssvr
      - name: run
        hostPath:
          path: /run
      - name: ca
        secret:
          secretName: root-ca
      - name: certgen
        secret:
          secretName: certgen
          defaultMode: 0744
      - name: certs
        hostPath:
          path: /etc/openness/certs/edgedns

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: syslog-ng
  namespace: openness
spec:
  selector:
    matchLabels:
      name: syslog-ng
  template:
    metadata:
      labels:
        name: syslog-ng
    spec:
      tolerations:
      - key: node-role.kube-ovn/master
        effect: NoSchedule
      containers:
      - name: syslog-ng
        image: balabit/syslog-ng:3.19.1
        imagePullPolicy: IfNotPresent
        args: ["--no-caps"]
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: syslog-conf
          mountPath: /etc/syslog-ng
          readOnly: true
        - name: certs
          mountPath: /etc/syslog-ng/certs
          readOnly: true
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: dockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      initContainers:
      - name: openssl
        image: emberstack/openssl:latest
        command: ["/root/certgen/entrypoint_tls.sh", "syslog.openness", "/root/certs", "/root/CA"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ca
          mountPath: /root/CA
        - name: certs
          mountPath: /root/certs
        - name: certgen
          mountPath: /root/certgen
      volumes:
      - name: syslog-conf
        configMap:
          name: syslog-conf
          items:
          - key: syslog-ng-k8s-worker.conf
            path: syslog-ng.conf
      - name: certs
        hostPath:
          path: /etc/openness/certs/syslog
      - name: log
        hostPath:
          path: /var/log
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: ca
        secret:
          secretName: root-ca
      - name: certgen
        secret:
          secretName: certgen
          defaultMode: 0744

---
apiVersion: v1
kind: Service
metadata:
  name: syslog-master
  namespace: openness
spec:
  clusterIP: None
  selector:
    name: syslog-master
  ports:
  - name: syslog
    protocol: UDP
    port: 6514
    targetPort: 6514

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: syslog-master
  namespace: openness
spec:
  selector:
    matchLabels:
      name: syslog-master
  template:
    metadata:
      labels:
        name: syslog-master
    spec:
      nodeSelector:
        kube-ovn/role: "master"
      tolerations:
      - operator: Exists
      containers:
      - name: syslog-ng
        image: balabit/syslog-ng:3.19.1
        imagePullPolicy: IfNotPresent
        args: ["--no-caps"]
        volumeMounts:
        - name: syslog-conf
          mountPath: /etc/syslog-ng
          readOnly: true
        - name: certs
          mountPath: /etc/syslog-ng/certs
          readOnly: true
        - name: log
          mountPath: /var/log
      initContainers:
      - name: openssl
        image: emberstack/openssl:latest
        command: ["/root/certgen/entrypoint_tls.sh", "syslog-master.openness", "/root/certs", "/root/CA"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ca
          mountPath: /root/CA
        - name: certs
          mountPath: /root/certs
        - name: certgen
          mountPath: /root/certgen
      volumes:
      - name: syslog-conf
        configMap:
          name: syslog-conf
          items:
          - key: syslog-ng-k8s-master.conf
            path: syslog-ng.conf
      - name: certs
        hostPath:
          path: /etc/openness/certs/syslog
      - name: log
        hostPath:
          path: /var/log/openness
      - name: ca
        secret:
          secretName: root-ca
      - name: certgen
        secret:
          secretName: certgen
          defaultMode: 0744

---
apiVersion: v1
kind: Service
metadata:
  name: interfaceservice
  namespace: openness
spec:
  clusterIP: None
  selector:
    name: interfaceservice
  ports:
  - name: interfaceservice
    protocol: TCP
    port: 42101
    targetPort: 42101

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: interfaceservice
  namespace: openness
spec:
  selector:
    matchLabels:
      name: interfaceservice
  template:
    metadata:
      labels:
        name: interfaceservice
    spec:
      tolerations:
      - key: node-role.kube-ovn/master
        effect: NoSchedule
      containers:
      - name: interfaceservice
        image: interfaceservice:1.0
        imagePullPolicy: Never
        securityContext:
          readOnlyRootFilesystem: true
          privileged: true
        volumeMounts:
        - name: configs
          mountPath: /home/interfaceservice/configs
          readOnly: true
        - name: certs
          mountPath: /home/interfaceservice/certs
          readOnly: true
        - name: host-netdevs
          mountPath: /var/host_net_devices
        - name: host-ns
          mountPath: /var/host_ns
          readOnly: true
        - name: devices
          mountPath: /devices
        - name: run
          mountPath: /var/run
      initContainers:
      - name: openssl
        image: emberstack/openssl:latest
        command: ["/root/certgen/entrypoint_tls.sh", "interfaceservice.openness", "/root/certs", "/root/CA"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ca
          mountPath: /root/CA
        - name: certs
          mountPath: /root/certs
        - name: certgen
          mountPath: /root/certgen
      volumes:
      - name: configs
        hostPath:
          path: /etc/openness/configs
      - name: certs
        hostPath:
          path: /etc/openness/certs/interfaceservice
      - name: host-netdevs
        hostPath:
          path: /sys/class/net
      - name: host-ns
        hostPath:
          path: /proc/1/ns
      - name: devices
        hostPath:
          path: /sys/devices
      - name: run
        hostPath:
          path: /var/run
      - name: ca
        secret:
          secretName: root-ca
      - name: certgen
        secret:
          secretName: certgen
          defaultMode: 0744
