---
- name: install git
  package:
    name:
      - git
    state: present

- name: create Controller directory
  file:
    path: "{{ controller_path }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: clone the controller-ce private repo
  git:
    repo: "https://{{ github_token }}@{{ repo_url }}"
    version: "{{ version }}"
    dest: "{{ controller_path }}"
    force: yes
  when: github_token != ""

- name: clone the controller-ce public repo
  git:
    repo: "https://{{ repo_url }}"
    version: "{{ version }}"
    dest: "{{ controller_path }}"
  when: github_token == ""

- name: configure .env
  template:
    src: env.j2
    dest: "{{ controller_path }}/.env"
    owner: "{{ ansible_user }}"
    mode: 0600

- name: set owner of Controller directory
  file:
    path: "{{ controller_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    recurse: yes
