---
- name: install make
  package:
    name: make
    state: present

- name: build UI
  make:
    chdir: "{{ controller_path }}"
    target: build
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: start the UI
  make:
    chdir: "{{ controller_path }}"
    target: ui-up
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: start the CUPS UI
  make:
    chdir: "{{ controller_path }}"
    target: cups-ui-up
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
