---
- name: install make and mysql client
  package:
    name:
      - make
      - mariadb
    state: present

- name: build controller
  make:
    chdir: "{{ controller_path }}"
    target: build
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: start the database
  make:
    chdir: "{{ controller_path }}"
    target: db-up
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: start the controller
  make:
    chdir: "{{ controller_path }}"
    target: cce-up
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
