---
- name: install docker prerequisites
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python-pip
    state: present

- name: install docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: install docker
  yum:
    name: docker-ce
    state: present

- name: enable and start docker
  service:
    name: docker
    enabled: yes
    state: started

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: install docker SDK
  pip:
    name: docker
